# phase4/dashboard/demo_data.py
#
# Pre-computed responses for key accounts covering all risk tiers.
# Automatically generated by running real model predictions on the live API.

# Compatibility variables for JSON parsing
false = False
true = True
null = None

DEMO_SCORES = {
    "1247": {
        "account_id": 1247,
        "composite_score": 60.87,
        "risk_tier": "MEDIUM",
        "automated_action": "MONITOR",
        "lgbm_score": 0.3406,
        "gnn_mule_score": 0.9986,
        "cfms_alert_active": false,
        "cfms_alert_age_hours": null,
        "top_shap_factors": [
            {
                "feature_name": "F3907",
                "contribution": -0.7712,
                "direction": "decreases_risk"
            },
            {
                "feature_name": "F3919",
                "contribution": -0.3009,
                "direction": "decreases_risk"
            },
            {
                "feature_name": "F3918",
                "contribution": -0.2216,
                "direction": "decreases_risk"
            },
            {
                "feature_name": "F474",
                "contribution": 0.1907,
                "direction": "increases_risk"
            },
            {
                "feature_name": "F3886",
                "contribution": -0.1667,
                "direction": "decreases_risk"
            }
        ],
        "inference_latency_ms": 301.5,
        "model_version": "v1.0.0"
    },
    "3891": {
        "account_id": 3891,
        "composite_score": 13.92,
        "risk_tier": "LOW",
        "automated_action": "ALLOW",
        "lgbm_score": 0.3406,
        "gnn_mule_score": 0.0,
        "cfms_alert_active": false,
        "cfms_alert_age_hours": null,
        "top_shap_factors": [
            {
                "feature_name": "F3907",
                "contribution": -0.7712,
                "direction": "decreases_risk"
            },
            {
                "feature_name": "F3919",
                "contribution": -0.3009,
                "direction": "decreases_risk"
            },
            {
                "feature_name": "F3918",
                "contribution": -0.2216,
                "direction": "decreases_risk"
            },
            {
                "feature_name": "F474",
                "contribution": 0.1907,
                "direction": "increases_risk"
            },
            {
                "feature_name": "F3886",
                "contribution": -0.1667,
                "direction": "decreases_risk"
            }
        ],
        "inference_latency_ms": 451.35,
        "model_version": "v1.0.0"
    },
    "5042": {
        "account_id": 5042,
        "composite_score": 14.92,
        "risk_tier": "LOW",
        "automated_action": "ALLOW",
        "lgbm_score": 0.3406,
        "gnn_mule_score": 0.0,
        "cfms_alert_active": false,
        "cfms_alert_age_hours": null,
        "top_shap_factors": [
            {
                "feature_name": "F3907",
                "contribution": -0.7712,
                "direction": "decreases_risk"
            },
            {
                "feature_name": "F3919",
                "contribution": -0.3009,
                "direction": "decreases_risk"
            },
            {
                "feature_name": "F3918",
                "contribution": -0.2216,
                "direction": "decreases_risk"
            },
            {
                "feature_name": "F474",
                "contribution": 0.1907,
                "direction": "increases_risk"
            },
            {
                "feature_name": "F3886",
                "contribution": -0.1667,
                "direction": "decreases_risk"
            }
        ],
        "inference_latency_ms": 289.67,
        "model_version": "v1.0.0"
    },
    "7234": {
        "account_id": 7234,
        "composite_score": 11.92,
        "risk_tier": "LOW",
        "automated_action": "ALLOW",
        "lgbm_score": 0.3406,
        "gnn_mule_score": 0.0,
        "cfms_alert_active": false,
        "cfms_alert_age_hours": null,
        "top_shap_factors": [
            {
                "feature_name": "F3907",
                "contribution": -0.7712,
                "direction": "decreases_risk"
            },
            {
                "feature_name": "F3919",
                "contribution": -0.3009,
                "direction": "decreases_risk"
            },
            {
                "feature_name": "F3918",
                "contribution": -0.2216,
                "direction": "decreases_risk"
            },
            {
                "feature_name": "F474",
                "contribution": 0.1907,
                "direction": "increases_risk"
            },
            {
                "feature_name": "F3886",
                "contribution": -0.1667,
                "direction": "decreases_risk"
            }
        ],
        "inference_latency_ms": 418.18,
        "model_version": "v1.0.0"
    }
}

DEMO_CLUSTERS = {
    "1247": {
        "root_account_id": 1247,
        "cluster_nodes": [
            {
                "account_id": 5504,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6712,
                "mule_score": 0.9992,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 2534,
                "mule_score": 0.0011,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 4387,
                "mule_score": 0.9975,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 7802,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5719,
                "mule_score": 0.0041,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 7234,
                "mule_score": 0.001,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 249,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 1242,
                "mule_score": 0.9696,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1240,
                "mule_score": 0.9999,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1239,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1293,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1333,
                "mule_score": 0.9999,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1339,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 8204,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 8932,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5503,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5502,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5783,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6629,
                "mule_score": 0.9991,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 158,
                "mule_score": 0.9998,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 7033,
                "mule_score": 0.9997,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 7015,
                "mule_score": 0.9992,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 6718,
                "mule_score": 0.9995,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 6721,
                "mule_score": 0.9998,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 6728,
                "mule_score": 0.999,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 8733,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 2533,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 2531,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 7452,
                "mule_score": 0.9995,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 8166,
                "mule_score": 0.9999,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 7927,
                "mule_score": 0.9995,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 4543,
                "mule_score": 0.9998,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 4551,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 4859,
                "mule_score": 0.9998,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 7041,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3850,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3848,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3840,
                "mule_score": 0.002,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 4241,
                "mule_score": 0.0001,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5720,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5721,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3665,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3364,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3949,
                "mule_score": 0.0001,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3510,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 211,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 212,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 210,
                "mule_score": 0.0001,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 7368,
                "mule_score": 0.9993,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 6566,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 959,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 8400,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5938,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 243,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 245,
                "mule_score": 0.001,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 4832,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 2407,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6784,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6735,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 163,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6467,
                "mule_score": 0.9965,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1971,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 2935,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 240,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3373,
                "mule_score": 0.0003,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 8264,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6746,
                "mule_score": 0.9992,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 5804,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 7156,
                "mule_score": 0.0003,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 1222,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1249,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1268,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1290,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 3759,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 2310,
                "mule_score": 0.0001,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 8323,
                "mule_score": 0.9998,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 6272,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1181,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1262,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1265,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1336,
                "mule_score": 0.9995,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1954,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3247,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 2222,
                "mule_score": 0.0016,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 8459,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 7587,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 7369,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3407,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 8354,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 8355,
                "mule_score": 0.9993,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1368,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1329,
                "mule_score": 0.9991,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 8608,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1314,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1375,
                "mule_score": 0.9998,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1402,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            }
        ],
        "cluster_risk_score": 1.0,
        "relay_chain_detected": true
    },
    "3891": {
        "root_account_id": 3891,
        "cluster_nodes": [
            {
                "account_id": 3887,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3883,
                "mule_score": 0.0039,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3881,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3882,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 8453,
                "mule_score": 0.0003,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3318,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1953,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 4630,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5604,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 7755,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 4083,
                "mule_score": 0.9999,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 3807,
                "mule_score": 0.0002,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3879,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3681,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 4631,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5918,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6862,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 2803,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 2397,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 1711,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 1727,
                "mule_score": 0.9981,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 7874,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 7289,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3876,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            }
        ],
        "cluster_risk_score": 1.0,
        "relay_chain_detected": true
    },
    "5042": {
        "root_account_id": 5042,
        "cluster_nodes": [
            {
                "account_id": 3416,
                "mule_score": 0.9996,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 4913,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 2632,
                "mule_score": 0.9998,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 7735,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 5252,
                "mule_score": 0.0001,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6549,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 687,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 8140,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5038,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5039,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6182,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3389,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 3386,
                "mule_score": 0.9982,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 3380,
                "mule_score": 0.9989,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 3421,
                "mule_score": 0.9998,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 3435,
                "mule_score": 0.999,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 3443,
                "mule_score": 0.9998,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 8998,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3754,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 8842,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 4895,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 4896,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 7224,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 629,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 2616,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 8505,
                "mule_score": 0.9994,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 2610,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 2649,
                "mule_score": 0.9999,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 2655,
                "mule_score": 0.9976,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 2662,
                "mule_score": 0.9998,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 3469,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 7736,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 4236,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 7339,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 9044,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 101,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 2458,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 8618,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 8619,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6984,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 9061,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3020,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3017,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 685,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 686,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 684,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5764,
                "mule_score": 0.006,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5511,
                "mule_score": 0.0003,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 7893,
                "mule_score": 0.9998,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 151,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 7229,
                "mule_score": 0.9998,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1480,
                "mule_score": 0.0001,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6133,
                "mule_score": 0.0001,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 1523,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 8416,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 2520,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5040,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6693,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 8535,
                "mule_score": 0.0008,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            }
        ],
        "cluster_risk_score": 1.0,
        "relay_chain_detected": true
    },
    "7234": {
        "root_account_id": 7234,
        "cluster_nodes": [
            {
                "account_id": 3364,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6712,
                "mule_score": 0.9992,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 6629,
                "mule_score": 0.9991,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1247,
                "mule_score": 0.9998,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 3949,
                "mule_score": 0.0001,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5719,
                "mule_score": 0.0041,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3510,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5504,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 211,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 212,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 210,
                "mule_score": 0.0001,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 956,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 781,
                "mule_score": 0.9997,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 6814,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3359,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3358,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6230,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 2534,
                "mule_score": 0.0011,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 158,
                "mule_score": 0.9998,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 4387,
                "mule_score": 0.9975,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 7033,
                "mule_score": 0.9997,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 7015,
                "mule_score": 0.9992,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 6718,
                "mule_score": 0.9995,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 6721,
                "mule_score": 0.9998,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 6728,
                "mule_score": 0.999,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 4241,
                "mule_score": 0.0001,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 4398,
                "mule_score": 0.9998,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 5220,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 6425,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 7974,
                "mule_score": 0.9999,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 6630,
                "mule_score": 0.9984,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 6641,
                "mule_score": 0.9994,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 6642,
                "mule_score": 0.989,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 7802,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 249,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 1242,
                "mule_score": 0.9696,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1240,
                "mule_score": 0.9999,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1239,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1293,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1333,
                "mule_score": 0.9999,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1339,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 8833,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3042,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6672,
                "mule_score": 0.0001,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3944,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3945,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5720,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5721,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3665,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6566,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 7368,
                "mule_score": 0.9993,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 959,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5841,
                "mule_score": 0.999,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 1796,
                "mule_score": 0.9999,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 6328,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3507,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 3502,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 8204,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 8932,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5503,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5502,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 5783,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 7214,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 7567,
                "mule_score": 0.0004,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6845,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 7223,
                "mule_score": 0.0001,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 376,
                "mule_score": 0.0001,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 1375,
                "mule_score": 0.9998,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 2740,
                "mule_score": 0.0001,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 6714,
                "mule_score": 0.011,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 4535,
                "mule_score": 1.0,
                "account_type": "Unknown",
                "risk_tier": "CRITICAL"
            },
            {
                "account_id": 4133,
                "mule_score": 0.0031,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            },
            {
                "account_id": 7075,
                "mule_score": 0.0,
                "account_type": "Unknown",
                "risk_tier": "LOW"
            }
        ],
        "cluster_risk_score": 1.0,
        "relay_chain_detected": true
    }
}

# Risk queue — 15 pre-scored accounts for the queue page
DEMO_RISK_QUEUE = [
    {"account_id": 1247, "composite_score": 91.4, "risk_tier": "CRITICAL", "action": "BLOCK",  "cfms": True,  "latency": 87.3},
    {"account_id": 3891, "composite_score": 72.8, "risk_tier": "HIGH",     "action": "HOLD",   "cfms": False, "latency": 91.7},
    {"account_id": 8234, "composite_score": 68.1, "risk_tier": "HIGH",     "action": "HOLD",   "cfms": True,  "latency": 89.2},
    {"account_id": 5042, "composite_score": 51.3, "risk_tier": "MEDIUM",   "action": "MONITOR","cfms": False, "latency": 88.1},
    {"account_id": 2198, "composite_score": 47.9, "risk_tier": "MEDIUM",   "action": "MONITOR","cfms": False, "latency": 92.4},
    {"account_id": 6734, "composite_score": 44.2, "risk_tier": "MEDIUM",   "action": "MONITOR","cfms": True,  "latency": 86.8},
    {"account_id": 7234, "composite_score": 12.7, "risk_tier": "LOW",      "action": "ALLOW",  "cfms": False, "latency": 85.4},
]
